const currencies = [
  {cc: 'AED', symbol: 'د.إ;', name: 'UAE dirham'},
  {cc: 'ARS', symbol: '$', name: 'Argentine peso'},
  {cc: 'AUD', symbol: '$', name: 'Australian dollar'},
  {cc: 'BDT', symbol: '৳', name: 'Bangladeshi taka'},
  {cc: 'BHD', symbol: '.د.ب', name: 'Bahraini dinar'},
  {cc: 'BMD', symbol: 'BD$', name: 'Bermudian dollar'},
  {cc: 'BRL', symbol: 'R$', name: 'Brazilian real'},
  {cc: 'CAD', symbol: '$', name: 'Canadian dollar'},
  {cc: 'CHF', symbol: 'Fr.', name: 'Swiss franc'},
  {cc: 'CLP', symbol: '$', name: 'Chilean peso'},
  {cc: 'CNY', symbol: '¥', name: 'Chinese/Yuan renminbi'},
  {cc: 'CZK', symbol: 'Kč', name: 'Czech koruna'},
  {cc: 'DKK', symbol: 'Kr', name: 'Danish krone'},
  {cc: 'EUR', symbol: '€', name: 'European Euro'},
  {cc: 'GBP', symbol: '£', name: 'British pound'},
  {cc: 'HKD', symbol: 'HK$', name: 'Hong Kong dollar'},
  {cc: 'HUF', symbol: 'Ft', name: 'Hungarian forint'},
  {cc: 'IDR', symbol: 'Rp', name: 'Indonesian rupiah'},
  {cc: 'ILS', symbol: '₪', name: 'Israeli new sheqel'},
  {cc: 'INR', symbol: '₹', name: 'Indian rupee'},
  {cc: 'JPY', symbol: '¥', name: 'Japanese yen'},
  {cc: 'KRW', symbol: 'W', name: 'South Korean won'},
  {cc: 'KWD', symbol: 'KWD', name: 'Kuwaiti dinar'},
  {cc: 'LKR', symbol: 'Rs', name: 'Sri Lankan rupee'},
  {cc: 'MMK', symbol: 'K', name: 'Myanma kyat'},
  {cc: 'MXN', symbol: '$', name: 'Mexican peso'},
  {cc: 'MYR', symbol: 'RM', name: 'Malaysian ringgit'},
  {cc: 'NGN', symbol: '₦', name: 'Nigerian naira'},
  {cc: 'NOK', symbol: 'kr', name: 'Norwegian krone'},
  {cc: 'NZD', symbol: 'NZ$', name: 'New Zealand dollar'},
  {cc: 'PHP', symbol: '₱', name: 'Philippine peso'},
  {cc: 'PKR', symbol: 'Rs.', name: 'Pakistani rupee'},
  {cc: 'PLN', symbol: 'zł', name: 'Polish zloty'},
  {cc: 'RUB', symbol: 'R', name: 'Russian ruble'},
  {cc: 'SAR', symbol: 'SR', name: 'Saudi riyal'},
  {cc: 'SEK', symbol: 'kr', name: 'Swedish krona'},
  {cc: 'SGD', symbol: 'S$', name: 'Singapore dollar'},
  {cc: 'THB', symbol: '฿', name: 'Thai baht'},
  {cc: 'TRY', symbol: 'TRY', name: 'Turkish new lira'},
  {cc: 'TWD', symbol: 'NT$', name: 'New Taiwan dollar'},
  {cc: 'UAH', symbol: 'UAH', name: 'Ukrainian hryvnia'},
  {cc: 'USD', symbol: 'US$', name: 'United States dollar'},
  {cc: 'VND', symbol: '₫', name: 'Vietnamese dong'},
  {cc: 'XDR', symbol: 'SDR', name: 'Special Drawing Rights'},
  {cc: 'ZAR', symbol: 'R', name: 'South African rand'},
];
export default currencies;
